// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/internal/proto/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_UNKNOWN   MessageStatus = 0
	MessageStatus_SENT      MessageStatus = 1
	MessageStatus_DELIVERED MessageStatus = 2
	MessageStatus_READ      MessageStatus = 3
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SENT",
		2: "DELIVERED",
		3: "READ",
	}
	MessageStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"SENT":      1,
		"DELIVERED": 2,
		"READ":      3,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_internal_proto_chat_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_api_internal_proto_chat_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{0}
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1Id       string                 `protobuf:"bytes,1,opt,name=user1_id,json=user1Id,proto3" json:"user1_id,omitempty"`
	User2Id       string                 `protobuf:"bytes,2,opt,name=user2_id,json=user2Id,proto3" json:"user2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRequest) GetUser1Id() string {
	if x != nil {
		return x.User1Id
	}
	return ""
}

func (x *CreateRoomRequest) GetUser2Id() string {
	if x != nil {
		return x.User2Id
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AlreadyExists bool                   `protobuf:"varint,2,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type RoomIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomIDRequest) Reset() {
	*x = RoomIDRequest{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomIDRequest) ProtoMessage() {}

func (x *RoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomIDRequest.ProtoReflect.Descriptor instead.
func (*RoomIDRequest) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *RoomIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type MessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Status        MessageStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=chatpb.MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *MessageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageInfo) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageInfo) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *MessageInfo) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_UNKNOWN
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageInfo         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryResponse) GetMessages() []*MessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageInfo           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetMessage() *MessageInfo {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        MessageStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=chatpb.MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_api_internal_proto_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_proto_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_internal_proto_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_UNKNOWN
}

var File_api_internal_proto_chat_proto protoreflect.FileDescriptor

const file_api_internal_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/internal/proto/chat.proto\x12\x06chatpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"I\n" +
	"\x11CreateRoomRequest\x12\x19\n" +
	"\buser1_id\x18\x01 \x01(\tR\auser1Id\x12\x19\n" +
	"\buser2_id\x18\x02 \x01(\tR\auser2Id\"T\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12%\n" +
	"\x0ealready_exists\x18\x02 \x01(\bR\ralreadyExists\"(\n" +
	"\rRoomIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xcb\x01\n" +
	"\vMessageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.chatpb.MessageStatusR\x06status\"B\n" +
	"\x0fHistoryResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.chatpb.MessageInfoR\bmessages\"C\n" +
	"\x12SendMessageRequest\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chatpb.MessageInfoR\amessage\"T\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.chatpb.MessageStatusR\x06status*?\n" +
	"\rMessageStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\b\n" +
	"\x04READ\x10\x032\x83\x02\n" +
	"\vChatService\x12C\n" +
	"\n" +
	"CreateRoom\x12\x19.chatpb.CreateRoomRequest\x1a\x1a.chatpb.CreateRoomResponse\x129\n" +
	"\aHistory\x12\x15.chatpb.RoomIDRequest\x1a\x17.chatpb.HistoryResponse\x128\n" +
	"\vSendMessage\x12\x1a.chatpb.SendMessageRequest\x1a\r.chatpb.Empty\x12:\n" +
	"\fUpdateStatus\x12\x1b.chatpb.UpdateStatusRequest\x1a\r.chatpb.EmptyB\tZ\a/chatpbb\x06proto3"

var (
	file_api_internal_proto_chat_proto_rawDescOnce sync.Once
	file_api_internal_proto_chat_proto_rawDescData []byte
)

func file_api_internal_proto_chat_proto_rawDescGZIP() []byte {
	file_api_internal_proto_chat_proto_rawDescOnce.Do(func() {
		file_api_internal_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_internal_proto_chat_proto_rawDesc), len(file_api_internal_proto_chat_proto_rawDesc)))
	})
	return file_api_internal_proto_chat_proto_rawDescData
}

var file_api_internal_proto_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_internal_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_internal_proto_chat_proto_goTypes = []any{
	(MessageStatus)(0),            // 0: chatpb.MessageStatus
	(*Empty)(nil),                 // 1: chatpb.Empty
	(*CreateRoomRequest)(nil),     // 2: chatpb.CreateRoomRequest
	(*CreateRoomResponse)(nil),    // 3: chatpb.CreateRoomResponse
	(*RoomIDRequest)(nil),         // 4: chatpb.RoomIDRequest
	(*MessageInfo)(nil),           // 5: chatpb.MessageInfo
	(*HistoryResponse)(nil),       // 6: chatpb.HistoryResponse
	(*SendMessageRequest)(nil),    // 7: chatpb.SendMessageRequest
	(*UpdateStatusRequest)(nil),   // 8: chatpb.UpdateStatusRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_internal_proto_chat_proto_depIdxs = []int32{
	9, // 0: chatpb.MessageInfo.sent_at:type_name -> google.protobuf.Timestamp
	0, // 1: chatpb.MessageInfo.status:type_name -> chatpb.MessageStatus
	5, // 2: chatpb.HistoryResponse.messages:type_name -> chatpb.MessageInfo
	5, // 3: chatpb.SendMessageRequest.message:type_name -> chatpb.MessageInfo
	0, // 4: chatpb.UpdateStatusRequest.status:type_name -> chatpb.MessageStatus
	2, // 5: chatpb.ChatService.CreateRoom:input_type -> chatpb.CreateRoomRequest
	4, // 6: chatpb.ChatService.History:input_type -> chatpb.RoomIDRequest
	7, // 7: chatpb.ChatService.SendMessage:input_type -> chatpb.SendMessageRequest
	8, // 8: chatpb.ChatService.UpdateStatus:input_type -> chatpb.UpdateStatusRequest
	3, // 9: chatpb.ChatService.CreateRoom:output_type -> chatpb.CreateRoomResponse
	6, // 10: chatpb.ChatService.History:output_type -> chatpb.HistoryResponse
	1, // 11: chatpb.ChatService.SendMessage:output_type -> chatpb.Empty
	1, // 12: chatpb.ChatService.UpdateStatus:output_type -> chatpb.Empty
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_internal_proto_chat_proto_init() }
func file_api_internal_proto_chat_proto_init() {
	if File_api_internal_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_internal_proto_chat_proto_rawDesc), len(file_api_internal_proto_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_internal_proto_chat_proto_goTypes,
		DependencyIndexes: file_api_internal_proto_chat_proto_depIdxs,
		EnumInfos:         file_api_internal_proto_chat_proto_enumTypes,
		MessageInfos:      file_api_internal_proto_chat_proto_msgTypes,
	}.Build()
	File_api_internal_proto_chat_proto = out.File
	file_api_internal_proto_chat_proto_goTypes = nil
	file_api_internal_proto_chat_proto_depIdxs = nil
}
