// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type UsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameRequest) Reset() {
	*x = UsernameRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameRequest) ProtoMessage() {}

func (x *UsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameRequest.ProtoReflect.Descriptor instead.
func (*UsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsResponse) Reset() {
	*x = UserExistsResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsResponse) ProtoMessage() {}

func (x *UserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsResponse.ProtoReflect.Descriptor instead.
func (*UserExistsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type NewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserRequest) Reset() {
	*x = NewUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRequest) ProtoMessage() {}

func (x *NewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRequest.ProtoReflect.Descriptor instead.
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *NewUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NewUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDResponse) Reset() {
	*x = UserIDResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDResponse) ProtoMessage() {}

func (x *UserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDResponse.ProtoReflect.Descriptor instead.
func (*UserIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsResponse) Reset() {
	*x = CredentialsResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsResponse) ProtoMessage() {}

func (x *CredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsResponse.ProtoReflect.Descriptor instead.
func (*CredentialsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialsResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fio           string                 `protobuf:"bytes,2,opt,name=fio,proto3" json:"fio,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Specialty     string                 `protobuf:"bytes,4,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Rating        float32                `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfileResponse) GetFio() string {
	if x != nil {
		return x.Fio
	}
	return ""
}

func (x *UserProfileResponse) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserProfileResponse) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *UserProfileResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UserProfileResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fio           string                 `protobuf:"bytes,2,opt,name=fio,proto3" json:"fio,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Specialty     string                 `protobuf:"bytes,4,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetFio() string {
	if x != nil {
		return x.Fio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateProfileRequest) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *UpdateProfileRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UserLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []string               `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	Requests      []string               `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLinksResponse) Reset() {
	*x = UserLinksResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinksResponse) ProtoMessage() {}

func (x *UserLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinksResponse.ProtoReflect.Descriptor instead.
func (*UserLinksResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserLinksResponse) GetTeachers() []string {
	if x != nil {
		return x.Teachers
	}
	return nil
}

func (x *UserLinksResponse) GetRequests() []string {
	if x != nil {
		return x.Requests
	}
	return nil
}

type AvailableTeachersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialty     string                 `protobuf:"bytes,1,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableTeachersRequest) Reset() {
	*x = AvailableTeachersRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableTeachersRequest) ProtoMessage() {}

func (x *AvailableTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableTeachersRequest.ProtoReflect.Descriptor instead.
func (*AvailableTeachersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *AvailableTeachersRequest) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *AvailableTeachersRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type UsersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProfileResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersListResponse) Reset() {
	*x = UsersListResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersListResponse) ProtoMessage() {}

func (x *UsersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersListResponse.ProtoReflect.Descriptor instead.
func (*UsersListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UsersListResponse) GetUsers() []*UserProfileResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type RelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationRequest) Reset() {
	*x = RelationRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationRequest) ProtoMessage() {}

func (x *RelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationRequest.ProtoReflect.Descriptor instead.
func (*RelationRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *RelationRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *RelationRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *BoolResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type StudentTeacherLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []string               `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	Students      []string               `protobuf:"bytes,2,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTeacherLinksResponse) Reset() {
	*x = StudentTeacherLinksResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTeacherLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTeacherLinksResponse) ProtoMessage() {}

func (x *StudentTeacherLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTeacherLinksResponse.ProtoReflect.Descriptor instead.
func (*StudentTeacherLinksResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *StudentTeacherLinksResponse) GetTeachers() []string {
	if x != nil {
		return x.Teachers
	}
	return nil
}

func (x *StudentTeacherLinksResponse) GetStudents() []string {
	if x != nil {
		return x.Students
	}
	return nil
}

type UpdateRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewRating     float32                `protobuf:"fixed32,2,opt,name=new_rating,json=newRating,proto3" json:"new_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRatingRequest) Reset() {
	*x = UpdateRatingRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatingRequest) ProtoMessage() {}

func (x *UpdateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatingRequest.ProtoReflect.Descriptor instead.
func (*UpdateRatingRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRatingRequest) GetNewRating() float32 {
	if x != nil {
		return x.NewRating
	}
	return 0
}

type RatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        float32                `protobuf:"fixed32,1,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingResponse) Reset() {
	*x = RatingResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingResponse) ProtoMessage() {}

func (x *RatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingResponse.ProtoReflect.Descriptor instead.
func (*RatingResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *RatingResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UUIDListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDListRequest) Reset() {
	*x = UUIDListRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDListRequest) ProtoMessage() {}

func (x *UUIDListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDListRequest.ProtoReflect.Descriptor instead.
func (*UUIDListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *UUIDListRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UUIDListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDListResponse) Reset() {
	*x = UUIDListResponse{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDListResponse) ProtoMessage() {}

func (x *UUIDListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDListResponse.ProtoReflect.Descriptor instead.
func (*UUIDListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *UUIDListResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\a\n" +
	"\x05Empty\"-\n" +
	"\x0fUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\",\n" +
	"\x12UserExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\\\n" +
	"\x0eNewUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\" \n" +
	"\x0eUserIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x12CredentialsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"9\n" +
	"\x13CredentialsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x1f\n" +
	"\rUserIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x95\x01\n" +
	"\x13UserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03fio\x18\x02 \x01(\tR\x03fio\x12\x10\n" +
	"\x03age\x18\x03 \x01(\rR\x03age\x12\x1c\n" +
	"\tspecialty\x18\x04 \x01(\tR\tspecialty\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x02R\x06rating\"~\n" +
	"\x14UpdateProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03fio\x18\x02 \x01(\tR\x03fio\x12\x10\n" +
	"\x03age\x18\x03 \x01(\rR\x03age\x12\x1c\n" +
	"\tspecialty\x18\x04 \x01(\tR\tspecialty\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\"K\n" +
	"\x11UserLinksResponse\x12\x1a\n" +
	"\bteachers\x18\x01 \x03(\tR\bteachers\x12\x1a\n" +
	"\brequests\x18\x02 \x03(\tR\brequests\"R\n" +
	"\x18AvailableTeachersRequest\x12\x1c\n" +
	"\tspecialty\x18\x01 \x01(\tR\tspecialty\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\"D\n" +
	"\x11UsersListResponse\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.user.UserProfileResponseR\x05users\"?\n" +
	"\x0fRelationRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\"&\n" +
	"\fBoolResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"U\n" +
	"\x1bStudentTeacherLinksResponse\x12\x1a\n" +
	"\bteachers\x18\x01 \x03(\tR\bteachers\x12\x1a\n" +
	"\bstudents\x18\x02 \x03(\tR\bstudents\"D\n" +
	"\x13UpdateRatingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"new_rating\x18\x02 \x01(\x02R\tnewRating\"(\n" +
	"\x0eRatingResponse\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\x02R\x06rating\"#\n" +
	"\x0fUUIDListRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"$\n" +
	"\x10UUIDListResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids2\xfa\b\n" +
	"\vUserService\x12=\n" +
	"\n" +
	"UserExists\x12\x15.user.UsernameRequest\x1a\x18.user.UserExistsResponse\x125\n" +
	"\aAddUser\x12\x14.user.NewUserRequest\x1a\x14.user.UserIDResponse\x12G\n" +
	"\x10CheckCredentials\x12\x18.user.CredentialsRequest\x1a\x19.user.CredentialsResponse\x12=\n" +
	"\vGetUserByID\x12\x13.user.UserIDRequest\x1a\x19.user.UserProfileResponse\x12<\n" +
	"\x11UpdateUserProfile\x12\x1a.user.UpdateProfileRequest\x1a\v.user.Empty\x12<\n" +
	"\fGetUserLinks\x12\x13.user.UserIDRequest\x1a\x17.user.UserLinksResponse\x12O\n" +
	"\x14GetAvailableTeachers\x12\x1e.user.AvailableTeachersRequest\x1a\x17.user.UsersListResponse\x127\n" +
	"\n" +
	"HasTeacher\x12\x15.user.RelationRequest\x1a\x12.user.BoolResponse\x12P\n" +
	"\x16GetStudentTeacherLinks\x12\x13.user.UserIDRequest\x1a!.user.StudentTeacherLinksResponse\x126\n" +
	"\fUpdateRating\x12\x19.user.UpdateRatingRequest\x1a\v.user.Empty\x126\n" +
	"\tGetRating\x12\x13.user.UserIDRequest\x1a\x14.user.RatingResponse\x124\n" +
	"\x0eAddRequestLink\x12\x15.user.RelationRequest\x1a\v.user.Empty\x123\n" +
	"\rAcceptRequest\x12\x15.user.RelationRequest\x1a\v.user.Empty\x121\n" +
	"\vDenyRequest\x12\x15.user.RelationRequest\x1a\v.user.Empty\x12:\n" +
	"\vGetRequests\x12\x13.user.UserIDRequest\x1a\x16.user.UUIDListResponse\x12?\n" +
	"\rGetUsersByIDs\x12\x15.user.UUIDListRequest\x1a\x17.user.UsersListResponse\x12D\n" +
	"\x14GetStudentsByTeacher\x12\x13.user.UserIDRequest\x1a\x17.user.UsersListResponse\x12D\n" +
	"\x14GetTeachersByStudent\x12\x13.user.UserIDRequest\x1a\x17.user.UsersListResponseB\tZ\a/userpbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: user.Empty
	(*UsernameRequest)(nil),             // 1: user.UsernameRequest
	(*UserExistsResponse)(nil),          // 2: user.UserExistsResponse
	(*NewUserRequest)(nil),              // 3: user.NewUserRequest
	(*UserIDResponse)(nil),              // 4: user.UserIDResponse
	(*CredentialsRequest)(nil),          // 5: user.CredentialsRequest
	(*CredentialsResponse)(nil),         // 6: user.CredentialsResponse
	(*UserIDRequest)(nil),               // 7: user.UserIDRequest
	(*UserProfileResponse)(nil),         // 8: user.UserProfileResponse
	(*UpdateProfileRequest)(nil),        // 9: user.UpdateProfileRequest
	(*UserLinksResponse)(nil),           // 10: user.UserLinksResponse
	(*AvailableTeachersRequest)(nil),    // 11: user.AvailableTeachersRequest
	(*UsersListResponse)(nil),           // 12: user.UsersListResponse
	(*RelationRequest)(nil),             // 13: user.RelationRequest
	(*BoolResponse)(nil),                // 14: user.BoolResponse
	(*StudentTeacherLinksResponse)(nil), // 15: user.StudentTeacherLinksResponse
	(*UpdateRatingRequest)(nil),         // 16: user.UpdateRatingRequest
	(*RatingResponse)(nil),              // 17: user.RatingResponse
	(*UUIDListRequest)(nil),             // 18: user.UUIDListRequest
	(*UUIDListResponse)(nil),            // 19: user.UUIDListResponse
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: user.UsersListResponse.users:type_name -> user.UserProfileResponse
	1,  // 1: user.UserService.UserExists:input_type -> user.UsernameRequest
	3,  // 2: user.UserService.AddUser:input_type -> user.NewUserRequest
	5,  // 3: user.UserService.CheckCredentials:input_type -> user.CredentialsRequest
	7,  // 4: user.UserService.GetUserByID:input_type -> user.UserIDRequest
	9,  // 5: user.UserService.UpdateUserProfile:input_type -> user.UpdateProfileRequest
	7,  // 6: user.UserService.GetUserLinks:input_type -> user.UserIDRequest
	11, // 7: user.UserService.GetAvailableTeachers:input_type -> user.AvailableTeachersRequest
	13, // 8: user.UserService.HasTeacher:input_type -> user.RelationRequest
	7,  // 9: user.UserService.GetStudentTeacherLinks:input_type -> user.UserIDRequest
	16, // 10: user.UserService.UpdateRating:input_type -> user.UpdateRatingRequest
	7,  // 11: user.UserService.GetRating:input_type -> user.UserIDRequest
	13, // 12: user.UserService.AddRequestLink:input_type -> user.RelationRequest
	13, // 13: user.UserService.AcceptRequest:input_type -> user.RelationRequest
	13, // 14: user.UserService.DenyRequest:input_type -> user.RelationRequest
	7,  // 15: user.UserService.GetRequests:input_type -> user.UserIDRequest
	18, // 16: user.UserService.GetUsersByIDs:input_type -> user.UUIDListRequest
	7,  // 17: user.UserService.GetStudentsByTeacher:input_type -> user.UserIDRequest
	7,  // 18: user.UserService.GetTeachersByStudent:input_type -> user.UserIDRequest
	2,  // 19: user.UserService.UserExists:output_type -> user.UserExistsResponse
	4,  // 20: user.UserService.AddUser:output_type -> user.UserIDResponse
	6,  // 21: user.UserService.CheckCredentials:output_type -> user.CredentialsResponse
	8,  // 22: user.UserService.GetUserByID:output_type -> user.UserProfileResponse
	0,  // 23: user.UserService.UpdateUserProfile:output_type -> user.Empty
	10, // 24: user.UserService.GetUserLinks:output_type -> user.UserLinksResponse
	12, // 25: user.UserService.GetAvailableTeachers:output_type -> user.UsersListResponse
	14, // 26: user.UserService.HasTeacher:output_type -> user.BoolResponse
	15, // 27: user.UserService.GetStudentTeacherLinks:output_type -> user.StudentTeacherLinksResponse
	0,  // 28: user.UserService.UpdateRating:output_type -> user.Empty
	17, // 29: user.UserService.GetRating:output_type -> user.RatingResponse
	0,  // 30: user.UserService.AddRequestLink:output_type -> user.Empty
	0,  // 31: user.UserService.AcceptRequest:output_type -> user.Empty
	0,  // 32: user.UserService.DenyRequest:output_type -> user.Empty
	19, // 33: user.UserService.GetRequests:output_type -> user.UUIDListResponse
	12, // 34: user.UserService.GetUsersByIDs:output_type -> user.UsersListResponse
	12, // 35: user.UserService.GetStudentsByTeacher:output_type -> user.UsersListResponse
	12, // 36: user.UserService.GetTeachersByStudent:output_type -> user.UsersListResponse
	19, // [19:37] is the sub-list for method output_type
	1,  // [1:19] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
