global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # балансер/лимитер, экспонирующий /metrics на localhost:8080
  - job_name: 'load_balancer'
    static_configs:
      - targets: ['172.17.0.1:8080']

  # системные метрики node_exporter (порт 9100, тоже на localhost)
  - job_name: 'node'
    static_configs:
      - targets: ['172.17.0.1:9100']
